# Generated by Django 3.2.25 on 2024-11-27 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_gamehistory'),
        ('users', '0002_userprofile_enabled_2fa'),
    ]

    operations = [
    ]
