# Generated by Django 3.2.25 on 2024-11-27 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_enabled_2fa'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='secret_2fa',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
