# Generated by Django 3.2.25 on 2024-11-27 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_merge_0002_gamehistory_0002_userprofile_enabled_2fa'),
        ('users', '0003_userprofile_secret_2fa'),
    ]

    operations = [
    ]
