# Generated by Django 3.2.25 on 2024-11-28 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_merge_20241127_1858'),
        ('users', '0004_merge_20241128_1228'),
    ]

    operations = [
    ]
