# Generated by Django 3.2.25 on 2024-11-29 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_merge_20241128_1428'),
        ('users', '0005_merge_20241128_1453'),
    ]

    operations = [
    ]
