# Generated by Django 3.2.25 on 2024-12-05 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_merge_20241128_1452'),
        ('users', '0007_userprofile_friends'),
    ]

    operations = [
    ]
