# Generated by Django 3.2.25 on 2024-12-06 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_gamehistory_score'),
        ('users', '0008_merge_20241205_1342'),
    ]

    operations = [
    ]
