# Generated by Django 3.2.25 on 2024-12-08 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_merge_20241206_1357'),
        ('users', '0009_merge_20241206_1433'),
    ]

    operations = [
    ]
